### ISSUE TITLE
Fix pipeline's circular dependencies

### ISSUE THREAD

**Issue by cabcookie** [cabcookie/potsdam-bot#9]
Error stack:

```
PotsdamBotContainerStack (potsdam-bot) failed: Error [ValidationError]: Circular dependency between resources: [PBotPipelineSourcecabcookiepotsdambotWebhookResource9B09F99B, PBotPipelineBuildSynthCdkBuildProjectC36C8989, PBotPipelineAssetsDockerAsset1CodePipelineActionRoleDefaultPolicy9A298303, PBotPipeline49BECE7A, PBotPipelineUpdatePipelineSelfMutationRoleDefaultPolicy0D046130, PBotPipelineBuildSynthCodePipelineActionRoleDefaultPolicy1D6C8553, PBotPipelineBuildSynthCdkBuildProjectRoleDefaultPolicyC1217D22, PBotPipelineUpdatePipelineSelfMutateCodePipelineActionRoleDefaultPolicyDB5A3F37, PBotPipelineUpdatePipelineSelfMutationA66841EE, PBotPipelineAssetsDockerAsset1737C1C82]
    at Request.extractError (/usr/local/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/protocol/query.js:50:29)
    at Request.callListeners (/usr/local/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/usr/local/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/usr/local/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/request.js:686:14)
    at Request.transition (/usr/local/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/usr/local/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /usr/local/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/usr/local/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/usr/local/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/request.js:688:12)
    at Request.callListeners (/usr/local/lib/node_modules/aws-cdk/node_modules/aws-sdk/lib/sequential_executor.js:116:18) {
      code: 'ValidationError',
      time: 2022-02-22T11:48:43.692Z,
      requestId: '3cd51505-9b0c-45d4-b83e-144bb4ae8a6d',
      statusCode: 400,
      retryable: false,
      retryDelay: 314.1119499383045
    }
Circular dependency between resources: [PBotPipelineSourcecabcookiepotsdambotWebhookResource9B09F99B, PBotPipelineBuildSynthCdkBuildProjectC36C8989, PBotPipelineAssetsDockerAsset1CodePipelineActionRoleDefaultPolicy9A298303, PBotPipeline49BECE7A, PBotPipelineUpdatePipelineSelfMutationRoleDefaultPolicy0D046130, PBotPipelineBuildSynthCodePipelineActionRoleDefaultPolicy1D6C8553, PBotPipelineBuildSynthCdkBuildProjectRoleDefaultPolicyC1217D22, PBotPipelineUpdatePipelineSelfMutateCodePipelineActionRoleDefaultPolicyDB5A3F37, PBotPipelineUpdatePipelineSelfMutationA66841EE, PBotPipelineAssetsDockerAsset1737C1C82]
```

**Comment by cabcookie** [comment]
The problem was, that the infrastructure had it's own package.json etc. Deleting those fixed the issue (see https://github.com/cabcookie/potsdam-bot/commit/e9feb107c3c6a0774c5f659a7c6cddf2cad36ad0).
